sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements-test.txt
script:
  - find . -type f -name \*.py -exec flake8 {} \;
  - python setup.py test
