language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - pip uninstall numpy -y || echo 'numpy not installed'
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy
  - pip install nose scikit-learn pep8
script:
  - make test
